In [1]:
import torch
import torch.nn.functional as F

In [26]:
dmodel_porojected = 512
# dmodel = 256
projection = torch.zeros(dmodel_porojected, dmodel_porojected)
mask = torch.eye(dmodel_porojected).bool()

projection = projection.masked_fill(mask, 0.5)

projection = projection[:, ::2] + projection[:, 1::2]
projection

tensor([[0.5000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.5000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.5000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.5000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.5000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.5000]])

In [31]:
dmodel_porojected = 512
# dmodel = 256
projection = torch.zeros(dmodel_porojected, dmodel_porojected)
mask = torch.eye(dmodel_porojected).bool()

projection = projection.masked_fill(mask, 1)

projection = projection[:, :int(dmodel_porojected/2)]
projection

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [2]:
p = torch.rand(512, 256)/256
pz = torch.zeros(512, 256)

# p = torch.rand(1, 2)
# pz = torch.zeros(1, 2)

projection_4 = torch.concat(
    (torch.concat((p, pz, pz, pz), dim=0),
    torch.concat((pz, p, pz, pz), dim=0),
    torch.concat((pz, pz, p, pz), dim=0),
    torch.concat((pz, pz, pz, p), dim=0),)
, dim=1)
# projection_4 = torch.concat((projection_4, projection_4, projection_4, projection_4), dim=1)
print(projection_4.shape)

w = torch.rand(2048, 512)

torch.Size([2048, 1024])


In [3]:
w.T.shape

torch.Size([512, 2048])

In [4]:
projection_4.T.shape

torch.Size([1024, 2048])

In [5]:
projection_4

tensor([[1.6405e-03, 4.9007e-04, 2.7963e-03,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [1.7257e-03, 3.0294e-03, 1.3402e-03,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [5.5414e-07, 1.0450e-03, 3.2509e-03,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        ...,
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 3.2722e-03, 2.0382e-03,
         4.3302e-04],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 3.2865e-03, 1.8893e-03,
         9.1997e-04],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 1.6485e-03, 7.0555e-04,
         1.9422e-03]])

In [6]:
(w.T@projection_4.T)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (512x2048 and 1024x2048)

In [13]:


torch.manual_seed(27)

# Example tensor of shape (1, 1, H, W)
DIM = 4
W = torch.rand(DIM, DIM)
P1 = torch.rand(int(DIM/2), DIM)
P2 = torch.rand(DIM, int(DIM/2))



In [16]:
P1.shape

torch.Size([2, 4])

In [17]:
W.shape

torch.Size([4, 4])

In [15]:
P1@W#@P2

tensor([[1.5872, 1.1626, 1.6426, 0.9742],
        [0.4341, 0.6854, 0.8121, 0.5155]])

In [73]:
i = torch.rand([100, 256])
p1 = torch.rand([512, 256]) #P torch.Size([256, 512])
w = torch.rand([1536, 512]) #W torch.Size([256, 1536])
p2 = torch.rand([768, 1536]) #P torch.Size([256, 768])

In [74]:
(i@p1.T@w.T@p2.T).shape

torch.Size([100, 768])

In [5]:
DIM1 = 12
DIM2 = 4
W = torch.rand(DIM1, DIM2)
P1 = torch.rand(int(DIM1/2), DIM1)
P2 = torch.rand(DIM2, int(DIM2/2))

In [6]:
r = P1@W@P2
print(W.shape)
print(r.shape)
r

torch.Size([12, 4])
torch.Size([6, 2])


tensor([[5.6443, 5.0776],
        [6.5575, 5.7987],
        [7.7880, 7.0714],
        [7.1346, 6.4522],
        [6.2099, 5.7591],
        [7.6796, 6.9450]])

In [28]:
DIM1 = 50257
DIM2 = 512
W = torch.rand(DIM1, DIM2)
P2 = torch.rand(DIM2, int(DIM2/2))

In [29]:
(W@P2).shape

torch.Size([502, 2])

In [7]:
# xb = 512
# yb = 2048
# xs = 256
# ys = 1024
# W = torch.rand(xb, yb)
# P1 = torch.rand(xs, xb)
# P2 = torch.rand(yb, ys)

# r = P1@W@P2
# print(W.shape)
# print(r.shape)
# r

In [9]:
from lizrd.core.misc import Linear


l = Linear(
    4, #xs
    8, #xb
    init_type = "kaiming_uniform",
    init_scale = 1.0
)
l

Linear(in_features=4, out_features=8, bias=False)