In [1]:
import torch
import torch.nn.functional as F

torch.manual_seed(27)

# Example tensor of shape (1, 1, H, W)
DIM = 4
W = torch.rand(DIM, DIM)
P1 = torch.rand(int(DIM/2), DIM)
P2 = torch.rand(DIM, int(DIM/2))



In [2]:
P1@W#@P2

tensor([[1.5872, 1.1626, 1.6426, 0.9742],
        [0.4341, 0.6854, 0.8121, 0.5155]])

In [3]:
DIM1 = 12
DIM2 = 4
W = torch.rand(DIM1, DIM2)
P1 = torch.rand(int(DIM1/2), DIM1)
P2 = torch.rand(DIM2, int(DIM2/2))

In [4]:
r = P1@W@P2
print(W.shape)
print(r.shape)
r

torch.Size([12, 4])
torch.Size([6, 2])


tensor([[5.6443, 5.0776],
        [6.5575, 5.7987],
        [7.7880, 7.0714],
        [7.1346, 6.4522],
        [6.2099, 5.7591],
        [7.6796, 6.9450]])

In [5]:
xb = 512
yb = 2048
xs = 256
ys = 1024
W = torch.rand(xb, yb)
P1 = torch.rand(xs, xb)
P2 = torch.rand(yb, ys)

In [6]:
r = P1@W@P2
print(W.shape)
print(r.shape)
r

torch.Size([512, 2048])
torch.Size([256, 1024])


tensor([[130796.1172, 128785.4453, 129663.6562,  ..., 128499.3594,
         130298.6484, 129971.3906],
        [133012.6562, 130936.7422, 131843.7656,  ..., 130729.7422,
         132476.1875, 132249.2500],
        [129721.0234, 127680.9062, 128570.0000,  ..., 127446.5781,
         129220.4062, 128920.0234],
        ...,
        [130213.5469, 128230.0234, 129112.5391,  ..., 127997.6562,
         129677.8828, 129393.8047],
        [130767.9375, 128707.3594, 129624.9375,  ..., 128489.2734,
         130267.7734, 129968.9062],
        [132819.5938, 130733.5156, 131616.2812,  ..., 130468.2188,
         132302.6875, 132004.3594]])

In [9]:
from lizrd.core.misc import Linear


l = Linear(
    4, #xs
    8, #xb
    init_type = "kaiming_uniform",
    init_scale = 1.0
)
l

Linear(in_features=4, out_features=8, bias=False)

In [11]:
l.weight

Parameter containing:
tensor([[-0.1175, -0.3492, -0.1019,  0.3333],
        [ 0.6530,  0.1067,  0.2894,  0.6535],
        [-0.6010,  0.2718, -0.0290,  0.3961],
        [ 0.8392,  0.4242, -0.7526,  0.2545],
        [-0.8204,  0.8378, -0.7909,  0.1884],
        [-0.8179,  0.0868,  0.5423, -0.1861],
        [-0.5960, -0.3729, -0.1753, -0.1666],
        [-0.6087,  0.0211,  0.4279,  0.2998]], requires_grad=True)

In [ ]:
from lizrd.train.train_utils import get_model


model = get_model(
        max_length=256,
        vocab_size=50048,
        block_modules=block_modules,
        dm=args.dmodel,
        n_blocks=args.n_blocks,
        device=(
            torch.device("cpu") if data_distributed else DEVICE
        ),  # in case of  DDP/FSDP, we initialize the model on CPU and move it to the GPU later
        init_type=args.init_type,
        init_scale=args.init_scale,
        ddp_enabled=args.ddp_enabled,
        fsdp_enabled=args.fsdp_enabled,
        fsdp_param_precision=fsdp_param_precision,
        fsdp_mixed_precision_ignore_classes=fsdp_mixed_precision_ignore_classes,
        fsdp_offload_params=args.fsdp_offload_params,
        fsdp_min_num_params=args.fsdp_min_num_params,
        fsdp_modules_to_wrap=fsdp_modules_to_wrap,
        activation_checkpointing_modules=activation_checkpointing_modules,
        model_fragmentation=args.model_parallelism_fragmentation,
        residual_fn=residual_fn,
        is_logging_process=is_logging_process,
        local_rank=local_rank,
        include_positional_embedding=(not args.no_positional_embedding)
        and (args.attention_mode != "rope"),
        checkpoint=checkpoint,
        projected_distillation = args.projected_distillation
    )