In [1]:
import torch
import torch.nn.functional as F

torch.manual_seed(27)

# Example tensor of shape (1, 1, H, W)
DIM = 4
W = torch.rand(DIM, DIM)
P1 = torch.rand(int(DIM/2), DIM)
P2 = torch.rand(DIM, int(DIM/2))



In [2]:
P1@W#@P2

tensor([[1.5872, 1.1626, 1.6426, 0.9742],
        [0.4341, 0.6854, 0.8121, 0.5155]])

In [3]:
DIM1 = 12
DIM2 = 4
W = torch.rand(DIM1, DIM2)
P1 = torch.rand(int(DIM1/2), DIM1)
P2 = torch.rand(DIM2, int(DIM2/2))

In [4]:
r = P1@W@P2
print(W.shape)
print(r.shape)
r

torch.Size([12, 4])
torch.Size([6, 2])


tensor([[5.6443, 5.0776],
        [6.5575, 5.7987],
        [7.7880, 7.0714],
        [7.1346, 6.4522],
        [6.2099, 5.7591],
        [7.6796, 6.9450]])

In [11]:
xb = 16
yb = 12
xs = 8
ys = 4
W = torch.rand(xb, yb)
P1 = torch.rand(xs, xb)
P2 = torch.rand(yb, ys)

In [12]:
r = P1@W@P2
print(W.shape)
print(r.shape)
r

torch.Size([16, 12])
torch.Size([8, 4])


tensor([[34.8887, 30.8061, 30.1453, 33.2653],
        [31.2322, 27.6122, 26.5922, 29.8460],
        [34.6945, 30.4678, 29.3001, 32.7113],
        [31.9785, 28.1054, 27.2621, 30.5219],
        [36.3048, 32.4781, 30.7391, 33.8942],
        [30.8029, 27.2439, 26.6532, 29.5020],
        [27.4554, 24.2086, 23.2463, 26.0006],
        [17.8547, 15.8166, 15.2549, 17.1449]])