In [3]:
import torch
import torch.nn.functional as F

In [4]:
6_800*4

27200

In [5]:
dmodel_porojected = 512
# dmodel = 256
projection = torch.zeros(dmodel_porojected, dmodel_porojected)
mask = torch.eye(dmodel_porojected).bool()

projection = projection.masked_fill(mask, 0.5)

projection = projection[:, ::2] + projection[:, 1::2]
projection

tensor([[0.5000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.5000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.5000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.5000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.5000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.5000]])

In [6]:
dmodel_porojected = 512
# dmodel = 256
projection = torch.zeros(dmodel_porojected, dmodel_porojected)
mask = torch.eye(dmodel_porojected).bool()

projection = projection.masked_fill(mask, 1)

projection = projection[:, :int(dmodel_porojected/2)]
projection

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [7]:
import torch
import torch.nn as nn

# Define the shape of the matrix
rows, cols = 5, 5

# Create a tensor with the desired shape
matrix = torch.empty(rows, cols)

# Initialize the tensor with an orthogonal matrix
nn.init.orthogonal_(matrix)

# Print the result
print("Orthogonal matrix:")
print(matrix)


Orthogonal matrix:
tensor([[-0.7757,  0.1727,  0.4806,  0.1165, -0.3520],
        [ 0.2687,  0.3110, -0.0160, -0.6212, -0.6670],
        [ 0.4237, -0.4287,  0.3395,  0.5095, -0.5118],
        [-0.1872,  0.1991, -0.7613,  0.4476, -0.3812],
        [ 0.3340,  0.8062,  0.2718,  0.3750,  0.1547]])


In [8]:
import torch
import torch.nn as nn

# Define the size of the matrix
rows, cols = 5, 5

# Create a random tensor with the desired shape
matrix = torch.empty(rows, cols)

# Initialize the matrix to be orthogonal
nn.init.orthogonal_(matrix)

# Normalize each column so that its sum equals 1
matrix = matrix / matrix.sum(dim=0, keepdim=True)

# Print the result
print("Orthogonal matrix with column sums equal to 1:")
print(matrix)
print("\nColumn sums:")
print(matrix.sum(dim=0))

Orthogonal matrix with column sums equal to 1:
tensor([[ 0.3460, -1.1121,  0.9585,  0.9917,  0.1774],
        [-0.8753,  0.2991,  0.7718, -0.7140,  0.3263],
        [ 0.0614,  1.4410,  0.4136,  1.1643,  0.0409],
        [ 1.3383,  0.4219,  0.3861, -0.8127,  0.1346],
        [ 0.1296, -0.0498, -1.5301,  0.3707,  0.3208]])

Column sums:
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


In [9]:
import torch
import torch.nn.functional as F

# Define the size of the matrix
rows, cols = 10, 5

# Step 1: Generate a random non-negative matrix
matrix = torch.rand(rows, cols)  # Values are uniformly sampled from [0, 1)

# Step 2: Normalize each column so that its sum equals 1
matrix = matrix / matrix.sum(dim=0, keepdim=True)

# Print the result
print("Matrix with non-negative values and column sums equal to 1:")
print(matrix)
print("\nColumn sums:")
print(matrix.sum(dim=0))

Matrix with non-negative values and column sums equal to 1:
tensor([[0.1466, 0.0457, 0.0547, 0.0187, 0.0623],
        [0.1311, 0.1760, 0.1589, 0.1041, 0.0663],
        [0.1024, 0.0671, 0.1403, 0.0975, 0.0037],
        [0.1421, 0.1780, 0.0897, 0.0365, 0.1042],
        [0.1438, 0.0445, 0.1861, 0.1528, 0.2133],
        [0.1157, 0.0513, 0.0281, 0.0771, 0.0369],
        [0.0030, 0.1039, 0.0141, 0.1467, 0.0176],
        [0.0952, 0.0308, 0.1059, 0.1574, 0.1836],
        [0.1112, 0.1466, 0.0946, 0.1497, 0.1681],
        [0.0088, 0.1562, 0.1275, 0.0594, 0.1440]])

Column sums:
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


In [10]:
p = torch.rand(512, 256)/256
pz = torch.zeros(512, 256)

# p = torch.rand(1, 2)
# pz = torch.zeros(1, 2)

projection_4 = torch.concat(
    (torch.concat((p, pz, pz, pz), dim=0),
    torch.concat((pz, p, pz, pz), dim=0),
    torch.concat((pz, pz, p, pz), dim=0),
    torch.concat((pz, pz, pz, p), dim=0),)
, dim=1)
# projection_4 = torch.concat((projection_4, projection_4, projection_4, projection_4), dim=1)
print(projection_4.shape)

w = torch.rand(2048, 512)

torch.Size([2048, 1024])


In [11]:
import torch

def approximate_orthogonal(rows, cols):
    # Step 1: Generate a random non-negative matrix
    matrix = torch.rand(rows, cols)
    
    # Step 2: Normalize columns to sum to 1
    matrix = matrix / matrix.sum(dim=0, keepdim=True)
    
    # Step 3: (Optional) Project onto orthogonal space (soft constraint)
    # This ensures matrix.T @ matrix is close to identity
    u, _, v = torch.svd(matrix)
    orthogonal_matrix = torch.mm(u, v.t())
    
    # Ensure non-negative and normalize columns again
    orthogonal_matrix = torch.clamp(orthogonal_matrix, min=0)
    orthogonal_matrix = orthogonal_matrix / orthogonal_matrix.sum(dim=0, keepdim=True)
    
    return orthogonal_matrix

# Example usage
rows, cols = 5, 5
approx_matrix = approximate_orthogonal(rows, cols)
print("Approximate Orthogonal Matrix with Non-Negative Values:")
print(approx_matrix)
print("\nColumn sums:")
print(approx_matrix.sum(dim=0))

Approximate Orthogonal Matrix with Non-Negative Values:
tensor([[0.1421, 0.0000, 0.0000, 0.0538, 0.8074],
        [0.0000, 0.4980, 0.1589, 0.2008, 0.1590],
        [0.4215, 0.2402, 0.0000, 0.3601, 0.0000],
        [0.3885, 0.2618, 0.3973, 0.0000, 0.0336],
        [0.0479, 0.0000, 0.4437, 0.3852, 0.0000]])

Column sums:
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


In [12]:
w.T.shape

torch.Size([512, 2048])

In [13]:
projection_4.T.shape

torch.Size([1024, 2048])

In [14]:
projection_4

tensor([[8.2097e-04, 5.4361e-04, 5.8225e-04,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [2.9144e-03, 8.1997e-05, 2.4070e-03,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [3.4595e-03, 3.1413e-03, 2.5275e-03,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        ...,
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 2.0823e-04, 1.2745e-03,
         2.9750e-03],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 2.4249e-03, 9.4952e-04,
         1.6059e-03],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 2.4418e-03, 2.4409e-03,
         2.0930e-03]])

In [15]:
(w.T@projection_4.T)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (512x2048 and 1024x2048)

In [13]:


torch.manual_seed(27)

# Example tensor of shape (1, 1, H, W)
DIM = 4
W = torch.rand(DIM, DIM)
P1 = torch.rand(int(DIM/2), DIM)
P2 = torch.rand(DIM, int(DIM/2))



In [16]:
P1.shape

torch.Size([2, 4])

In [17]:
W.shape

torch.Size([4, 4])

In [15]:
P1@W#@P2

tensor([[1.5872, 1.1626, 1.6426, 0.9742],
        [0.4341, 0.6854, 0.8121, 0.5155]])

In [73]:
i = torch.rand([100, 256])
p1 = torch.rand([512, 256]) #P torch.Size([256, 512])
w = torch.rand([1536, 512]) #W torch.Size([256, 1536])
p2 = torch.rand([768, 1536]) #P torch.Size([256, 768])

In [74]:
(i@p1.T@w.T@p2.T).shape

torch.Size([100, 768])

In [5]:
DIM1 = 12
DIM2 = 4
W = torch.rand(DIM1, DIM2)
P1 = torch.rand(int(DIM1/2), DIM1)
P2 = torch.rand(DIM2, int(DIM2/2))

In [6]:
r = P1@W@P2
print(W.shape)
print(r.shape)
r

torch.Size([12, 4])
torch.Size([6, 2])


tensor([[5.6443, 5.0776],
        [6.5575, 5.7987],
        [7.7880, 7.0714],
        [7.1346, 6.4522],
        [6.2099, 5.7591],
        [7.6796, 6.9450]])

In [28]:
DIM1 = 50257
DIM2 = 512
W = torch.rand(DIM1, DIM2)
P2 = torch.rand(DIM2, int(DIM2/2))

In [29]:
(W@P2).shape

torch.Size([502, 2])

In [7]:
# xb = 512
# yb = 2048
# xs = 256
# ys = 1024
# W = torch.rand(xb, yb)
# P1 = torch.rand(xs, xb)
# P2 = torch.rand(yb, ys)

# r = P1@W@P2
# print(W.shape)
# print(r.shape)
# r

In [2]:
100663296/256/256/8

192.0

In [9]:
from lizrd.core.misc import Linear


l = Linear(
    4, #xs
    8, #xb
    init_type = "kaiming_uniform",
    init_scale = 1.0
)
l

Linear(in_features=4, out_features=8, bias=False)

In [16]:
W = torch.rand([256, 256, 1536])

P = 

tensor([[[0.4112, 0.3712, 0.7074,  ..., 0.2067, 0.3223, 0.6609],
         [0.1767, 0.0279, 0.6210,  ..., 0.5603, 0.5550, 0.9668],
         [0.4712, 0.5512, 0.1143,  ..., 0.6889, 0.4279, 0.3702],
         ...,
         [0.0687, 0.6255, 0.9915,  ..., 0.0017, 0.2993, 0.0796],
         [0.8611, 0.4290, 0.0277,  ..., 0.3237, 0.2262, 0.4244],
         [0.4213, 0.1870, 0.7985,  ..., 0.2079, 0.7280, 0.0180]],

        [[0.3812, 0.2659, 0.3248,  ..., 0.6246, 0.1632, 0.9463],
         [0.3213, 0.0730, 0.4806,  ..., 0.5851, 0.6259, 0.7696],
         [0.9133, 0.3310, 0.9434,  ..., 0.5543, 0.8915, 0.9186],
         ...,
         [0.8282, 0.9274, 0.7947,  ..., 0.9190, 0.8918, 0.9438],
         [0.6023, 0.3419, 0.9875,  ..., 0.3250, 0.9732, 0.0913],
         [0.6401, 0.2204, 0.2960,  ..., 0.0160, 0.1634, 0.4017]],

        [[0.7399, 0.1116, 0.4881,  ..., 0.9887, 0.4190, 0.8412],
         [0.6753, 0.9980, 0.3465,  ..., 0.1326, 0.5735, 0.4071],
         [0.3257, 0.8010, 0.2999,  ..., 0.3211, 0.5564, 0.