In [1]:
import torch
import torch.nn.functional as F

In [13]:


torch.manual_seed(27)

# Example tensor of shape (1, 1, H, W)
DIM = 4
W = torch.rand(DIM, DIM)
P1 = torch.rand(int(DIM/2), DIM)
P2 = torch.rand(DIM, int(DIM/2))



In [16]:
P1.shape

torch.Size([2, 4])

In [17]:
W.shape

torch.Size([4, 4])

In [15]:
P1@W#@P2

tensor([[1.5872, 1.1626, 1.6426, 0.9742],
        [0.4341, 0.6854, 0.8121, 0.5155]])

In [ ]:
torch.Size(([B, 256])
torch.Size(([512, 256]) P torch.Size([256, 512])
torch.Size([1536, 512]) W
torch.Size([768, 1536]) P

In [63]:
(torch.rand([256, 256])@torch.rand([512, 256]).T).shape

torch.Size([256, 512])

In [49]:
(torch.rand([512, 256])@torch.rand([1536, 512])).shape

RuntimeError: mat1 and mat2 shapes cannot be multiplied (512x256 and 1536x512)

In [ ]:
torch.Size([512, 256])
torch.Size([1536, 512])
torch.Size([768, 1536])

In [52]:
F.linear(torch.rand([512, 256]), torch.rand([1536, 512]), None)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (512x256 and 512x1536)

In [55]:
torch.rand([256, 256])@torch.rand([512, 256])

RuntimeError: mat1 and mat2 shapes cannot be multiplied (256x256 and 512x256)

In [54]:
F.linear(torch.rand([256, 256]), torch.rand([512, 256]), None)

tensor([[63.7471, 65.5120, 64.5740,  ..., 66.3840, 62.7879, 66.8063],
        [62.9364, 69.3876, 64.5420,  ..., 67.1863, 62.3899, 68.8020],
        [58.3661, 59.6192, 62.6625,  ..., 60.3173, 58.3739, 61.0304],
        ...,
        [62.4567, 67.6043, 66.0833,  ..., 63.7117, 61.7524, 62.3698],
        [61.7911, 64.4922, 66.5581,  ..., 68.8840, 63.2886, 64.1588],
        [61.4019, 66.3939, 64.6481,  ..., 64.6506, 62.4653, 65.3930]])

In [5]:
DIM1 = 12
DIM2 = 4
W = torch.rand(DIM1, DIM2)
P1 = torch.rand(int(DIM1/2), DIM1)
P2 = torch.rand(DIM2, int(DIM2/2))

In [6]:
r = P1@W@P2
print(W.shape)
print(r.shape)
r

torch.Size([12, 4])
torch.Size([6, 2])


tensor([[5.6443, 5.0776],
        [6.5575, 5.7987],
        [7.7880, 7.0714],
        [7.1346, 6.4522],
        [6.2099, 5.7591],
        [7.6796, 6.9450]])

In [28]:
DIM1 = 50257
DIM2 = 512
W = torch.rand(DIM1, DIM2)
P2 = torch.rand(DIM2, int(DIM2/2))

In [29]:
(W@P2).shape

torch.Size([502, 2])

In [31]:
P2

tensor([[0.6864, 0.3059],
        [0.6783, 0.0089],
        [0.8684, 0.8320],
        [0.6172, 0.5390],
        [0.8979, 0.8956]])

In [7]:
# xb = 512
# yb = 2048
# xs = 256
# ys = 1024
# W = torch.rand(xb, yb)
# P1 = torch.rand(xs, xb)
# P2 = torch.rand(yb, ys)

# r = P1@W@P2
# print(W.shape)
# print(r.shape)
# r

In [9]:
from lizrd.core.misc import Linear


l = Linear(
    4, #xs
    8, #xb
    init_type = "kaiming_uniform",
    init_scale = 1.0
)
l

Linear(in_features=4, out_features=8, bias=False)

In [22]:
# from lizrd.train.train_utils import get_model
# from research.conditional.utils.model_utils import get_ff_layer
# from research.projected_distillation.llm import ProjectedFeedForward
# dmodel = 256
# dff = 1024
# projected_dmodel = dmodel*2
# projected_dff = dff*2
# n_blocks = 8
# init_type = "kaiming_uniform"
# init_scale= 1.0
# block_modules = {
#     "FF": lambda: ProjectedFeedForward(
#             dmodel, dff, projected_dmodel, projected_dff, init_type=init_type, init_scale= init_scale
#         ),
#     "Attention": 
# }

# model = get_model(
#         max_length=256,
#         vocab_size=50048,
#         block_modules=block_modules,
#         dm=dmodel,
#         n_blocks=n_blocks,
#         device=(
#             torch.device("cuda")
#         ),  # in case of  DDP/FSDP, we initialize the model on CPU and move it to the GPU later
#         init_type=init_type,
#         init_scale=init_scale,
#         ddp_enabled=False,
#         fsdp_enabled=False,
#         fsdp_param_precision=False,
#         fsdp_mixed_precision_ignore_classes=False,
#         fsdp_offload_params=False,
#         fsdp_min_num_params=False,
#         fsdp_modules_to_wrap=False,
#         activation_checkpointing_modules=False,
#     )

SyntaxError: expression expected after dictionary key and ':' (902681333.py, line 15)