In [3]:
from fancy_einsum import einsum
import torch

In [11]:
x = torch.tensor([[[1, 2], [3, 28], [7, 2]], [[1, 2], [3, 28], [7, 2]], [[1, 2], [3, 28], [7, 2]], [[1, 2], [3, 28], [7, 2]]])

In [12]:
print(x.shape)
batch_size, seq_len, dmodel = x.shape

torch.Size([4, 3, 2])


In [7]:
y = torch.tensor([3, 4, 5, 7])
y = y.view(-1, 1, 1)
print(y)
print(x * y)

tensor([[[3]],

        [[4]],

        [[5]],

        [[7]]])
tensor([[[  3,   6],
         [  9,  84],
         [ 21,   6]],

        [[  4,   8],
         [ 12, 112],
         [ 28,   8]],

        [[  5,  10],
         [ 15, 140],
         [ 35,  10]],

        [[  7,  14],
         [ 21, 196],
         [ 49,  14]]])


In [19]:
z = x.reshape(1, batch_size * seq_len, dmodel)
z = z.repeat(10, 1, 1)
print(z.shape)

torch.Size([10, 12, 2])


In [2]:
import torch

# Create a tensor of shape (1, 2, 3)
x = torch.randn(1, 2, 3)

# Ensure the shape is correct
assert x.shape == (1, 2, 3)

# Repeat the tensor 10 times along the first dimension
repeated_tensor = x.repeat(10, 1, 1)

# Check the shape of the new tensor
print(repeated_tensor.shape)  # Output should be torch.Size([10, 2, 3])



torch.Size([10, 2, 3])


In [3]:
toks = repeated_tensor[0:2, 1:3]
toks

tensor([[[ 1.3546, -0.5888,  0.7038]],

        [[ 1.3546, -0.5888,  0.7038]]])