In [2]:
import numpy as np
import torch

In [8]:
def print_tup(tup):
    for t in tup:
        print(t)

In [11]:
tokens = torch.tensor([[1, 2, 3], [-1, -1, 0]], dtype=torch.float).T
print(tokens)

tensor([[ 1., -1.],
        [ 2., -1.],
        [ 3.,  0.]])


In [12]:
W_v = torch.tensor([[1, 1, 1],
                    [0, 0, 1],
                    [0, 1, -1]], dtype=torch.float)
W_o = torch.tensor([[2, 0, -1],
                    [0, 1, 0],
                    [3, 0, 1]], dtype=torch.float)
A = torch.tensor([[0.6, 0.4],
                  [0.1, 0.9]], dtype=torch.float)
print(f'W_v: {W_v}')
print(f'W_o: {W_o}')
print(f'A: {A}')

W_v: tensor([[ 1.,  1.,  1.],
        [ 0.,  0.,  1.],
        [ 0.,  1., -1.]])
W_o: tensor([[ 2.,  0., -1.],
        [ 0.,  1.,  0.],
        [ 3.,  0.,  1.]])
A: tensor([[0.6000, 0.4000],
        [0.1000, 0.9000]])


In [17]:
def att_mm(x):
    v = torch.matmul(W_v, x)
    weighted = torch.matmul(v, A.T)
    out = torch.matmul(W_o, weighted)
    return out, weighted, v

def att_tp(x):
    e_dim = torch.matmul(W_o, W_v)
    out1 = torch.matmul(torch.matmul(e_dim, x), A.T)
    out2 = torch.matmul(e_dim, torch.matmul(x, A.T))
    return out1, out2

In [18]:
mm_out = att_mm(tokens)
tp_out = att_tp(tokens)

print_tup(mm_out)
print()
print_tup(tp_out)

tensor([[ 6.6000, -1.4000],
        [ 1.8000,  0.3000],
        [ 7.4000, -4.6000]])
tensor([[ 2.8000, -1.2000],
        [ 1.8000,  0.3000],
        [-1.0000, -1.0000]])
tensor([[ 6., -2.],
        [ 3.,  0.],
        [-1., -1.]])

tensor([[ 6.6000, -1.4000],
        [ 1.8000,  0.3000],
        [ 7.4000, -4.6000]])
tensor([[ 6.6000, -1.4000],
        [ 1.8000,  0.3000],
        [ 7.4000, -4.6000]])
