In [61]:
import random


def select_non_contiguous_indexes(n, available_indexes: list):
    """
    Select n non-contiguous indexes from a list of available indexes.
    """

    if len(available_indexes) != len(set(available_indexes)):
        raise ValueError("Available indexes must be unique.")

    if not available_indexes:
        raise ValueError("Available indexes must not be empty.")

    selected = []
    while len(selected) < n and available_indexes:
        selected_element = random.choice(available_indexes)
        selected.append(selected_element)

        # Update the available list to maintain the non-contiguity constraint
        new_available = []
        for element in available_indexes:
            if abs(selected_element - element) > 1:
                new_available.append(element)
        available_indexes = new_available

    if len(selected) < n:
        raise ValueError("Not enough non-contiguous indexes available.")

    return selected

In [71]:
select_non_contiguous_indexes(3, [1, 5, 6, 7])

ValueError: Not enough non-contiguous indexes available.

In [22]:
select_non_contiguous_indexes(3, [])

ValueError: Available indexes must not be empty.

In [21]:
select_non_contiguous_indexes(3, [1, 2, 4, 5, 6, 1])

ValueError: Available indexes must be unique.

In [79]:
import numpy as np

arr = np.array([[10, 20, 10], [30, 40, 50], [10, 60, 70], [80, 90, 10]])
print(np.where(arr == 10))

(array([0, 0, 2, 3]), array([0, 2, 0, 2]))


In [80]:
np.where(arr == 10)

(array([0, 0, 2, 3]), array([0, 2, 0, 2]))

In [84]:
(arr == 10).nonzero()

(array([0, 0, 2, 3]), array([0, 2, 0, 2]))

In [85]:
arr == 10

array([[ True, False,  True],
       [False, False, False],
       [ True, False, False],
       [False, False,  True]])

In [89]:
result = [np.where(sequence == 10)[0] for sequence in arr]

In [91]:
result

array([], dtype=int64)

In [93]:
np.where(np.array([10, 60, 70]) == 10)

(array([0]),)

In [95]:
import torch

ok = torch.tensor(
    [
        [
            3015,
            329,
            607,
            45581,
            290,
            7101,
            606,
            286,
            607,
            18410,
            11,
            2739,
            5537,
            4139,
            1423,
            8704,
            22081,
            13,
            4389,
            88,
            15927,
            318,
            11643,
            284,
            8414,
            422,
            37399,
            14225,
            11,
            3461,
            324,
            17325,
        ],
        [
            1327,
            640,
            27074,
            616,
            1182,
            1088,
            262,
            2126,
            326,
            11,
            379,
            617,
            966,
            11,
            661,
            655,
            2245,
            4673,
            13,
            198,
            10374,
            1806,
            617,
            1611,
            286,
            27886,
            393,
            584,
            5110,
            8967,
            11,
            340,
        ],
        [
            25,
            1578,
            7526,
            13,
            198,
            32,
            2092,
            6538,
            2648,
            3038,
            7791,
            7160,
            329,
            1402,
            2706,
            287,
            262,
            3482,
            11,
            1900,
            355,
            262,
            14973,
            8549,
            554,
            1087,
            425,
            1169,
            3620,
            40,
            13,
            383,
        ],
        [
            522,
            9382,
            319,
            1938,
            290,
            37924,
            11,
            355,
            880,
            355,
            257,
            23714,
            9552,
            326,
            1838,
            340,
            4622,
            7069,
            284,
            4776,
            4661,
            1377,
            262,
            6678,
            16608,
            319,
            262,
            24169,
            2650,
            13,
            3244,
            345,
        ],
        [
            33801,
            378,
            616,
            3159,
            475,
            4724,
            644,
            13,
            632,
            318,
            477,
            991,
            257,
            4724,
            13,
            921,
            423,
            645,
            2126,
            644,
            1243,
            481,
            804,
            588,
            1566,
            484,
            389,
            1682,
            319,
            3348,
            13,
            198,
        ],
        [
            517,
            6851,
            588,
            428,
            13,
            198,
            2025,
            8036,
            2648,
            11,
            314,
            2391,
            1813,
            428,
            4291,
            257,
            16008,
            508,
            373,
            1804,
            6454,
            3781,
            319,
            428,
            13,
            843,
            339,
            287,
            3872,
            8155,
            502,
            12607,
        ],
        [
            447,
            247,
            82,
            617,
            5986,
            286,
            1486,
            4213,
            329,
            534,
            1363,
            11087,
            1486,
            3519,
            284,
            1588,
            16610,
            17423,
            3084,
            13,
            775,
            7723,
            262,
            4263,
            422,
            2972,
            4237,
            284,
            2148,
            360,
            3191,
            10096,
        ],
        [
            9009,
            293,
            290,
            18340,
            351,
            9580,
            12983,
            13,
            16374,
            1257,
            1027,
            33173,
            351,
            326,
            698,
            278,
            4813,
            1842,
            13,
            2905,
            33173,
            1282,
            287,
            40003,
            2042,
            47750,
            2612,
            6979,
            3091,
            0,
            50256,
            464,
        ],
    ]
)

In [97]:
ok == 0

tensor([[False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False],
        [False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False],
        [False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False],
        [False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, F

In [98]:
heh = ok == 0

In [99]:
heh

tensor([[False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False],
        [False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False],
        [False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False],
        [False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, F

In [117]:
mhym = heh.nonzero(as_tuple=True)

In [110]:
mhym

tensor([[ 7, 29]])

In [113]:
ok.index_select(0, mhym)

IndexError: index_select(): Index is supposed to be a vector

In [115]:
torch.where(ok == 0)

(tensor([7]), tensor([29]))

In [118]:
ok[mhym]

tensor([0])

In [123]:
torch.take(ok, torch.tensor([33, 35, 65]))

tensor([ 640,  616, 1578])